name: Build FydeOS for OrangePi5b

on:
  push:                     # 每次推送代码自动触发构建
    branches:
      - main
  workflow_dispatch:        # 也可以在 GitHub 网页手动点击“Run workflow”触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Build Environment
        run: |
          sudo apt update
          sudo apt install -y wget xz-utils

      - name: Download openFyde .run Installer
        run: |
          wget https://github.com/openFyde/overlay-orangepi5-openfyde/releases/download/r132/orangepi5-openfyde-r132.run -O fydeos.run
          chmod +x fydeos.run

      - name: Generate FydeOS IMG (OrangePi5B, eMMC/raw)
        run: |
          ./fydeos.run --board orangepi5b --boot raw

      - name: List Generated Files
        run: ls -lh *.img || echo "No image generated"

      - name: Upload Generated Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FydeOS-OrangePi5B-IMG
          path: "*.img"
          retention-days: 7
