name: Build openFyde r126 for OrangePi5B (eMMC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y wget xz-utils

      - name: Download openFyde r126 installer
        run: |
          wget https://github.com/openFyde/overlay-orangepi5-openfyde/releases/download/r126/orangepi5-openfyde-r126.run -O openfyde126.run
          chmod +x openfyde126.run

      - name: Generate eMMC IMG (r126)
        run: |
          ./openfyde126.run --board orangepi5b --boot emmc

      - name: List output
        run: ls -lh *.img || echo "No image produced"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openfyde-OrangePi5B-r126-emmc
          path: "*.img"
          retention-days: 7
